/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EADNINJA_AUTODEFS_H
#define S3EADNINJA_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ADNINJA_NAME "s3eAdNinja"
#define S3E_EXT_ADNINJA_HASH 0x8d477245

#endif /* !S3EADNINJA_AUTODEFS_H */
