/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "s3eAdNinja.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*s3eAdNinjaRegister_t)(s3eAdNinjaCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*s3eAdNinjaUnRegister_t)(s3eAdNinjaCallback cbid, s3eCallback fn);
typedef  s3eResult(*s3eAdNinjaStart_t)(const char* appKey);
typedef  s3eResult(*s3eAdNinjaRequestFreshAd_t)();
typedef  s3eResult(*s3eAdNinjaShow_t)();
typedef  s3eResult(*s3eAdNinjaHide_t)();

/**
 * struct that gets filled in by s3eAdNinjaRegister
 */
typedef struct s3eAdNinjaFuncs
{
    s3eAdNinjaRegister_t m_s3eAdNinjaRegister;
    s3eAdNinjaUnRegister_t m_s3eAdNinjaUnRegister;
    s3eAdNinjaStart_t m_s3eAdNinjaStart;
    s3eAdNinjaRequestFreshAd_t m_s3eAdNinjaRequestFreshAd;
    s3eAdNinjaShow_t m_s3eAdNinjaShow;
    s3eAdNinjaHide_t m_s3eAdNinjaHide;
} s3eAdNinjaFuncs;

static s3eAdNinjaFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x8d477245, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: s3eAdNinja");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x8d477245, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eAdNinjaAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult s3eAdNinjaRegister(s3eAdNinjaCallback cbid, s3eCallback fn, void* userData)
{
    IwTrace(ADNINJA_VERBOSE, ("calling s3eAdNinja[0] func: s3eAdNinjaRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdNinjaRegister(cbid, fn, userData);
}

s3eResult s3eAdNinjaUnRegister(s3eAdNinjaCallback cbid, s3eCallback fn)
{
    IwTrace(ADNINJA_VERBOSE, ("calling s3eAdNinja[1] func: s3eAdNinjaUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdNinjaUnRegister(cbid, fn);
}

s3eResult s3eAdNinjaStart(const char* appKey)
{
    IwTrace(ADNINJA_VERBOSE, ("calling s3eAdNinja[2] func: s3eAdNinjaStart"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdNinjaStart(appKey);
}

s3eResult s3eAdNinjaRequestFreshAd()
{
    IwTrace(ADNINJA_VERBOSE, ("calling s3eAdNinja[3] func: s3eAdNinjaRequestFreshAd"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdNinjaRequestFreshAd();
}

s3eResult s3eAdNinjaShow()
{
    IwTrace(ADNINJA_VERBOSE, ("calling s3eAdNinja[4] func: s3eAdNinjaShow"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdNinjaShow();
}

s3eResult s3eAdNinjaHide()
{
    IwTrace(ADNINJA_VERBOSE, ("calling s3eAdNinja[5] func: s3eAdNinjaHide"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdNinjaHide();
}
